CAMP_SOURCES = [
    {
        "source_key": "city_victoria_camps",
        "name": "City of Victoria Recreation",
        "municipality": "Victoria",
        "venue_names": ["Crystal Pool and Fitness Centre", "Victoria community centres"],
        "primary_url": "https://www.victoria.ca/parks-recreation/recreation",
        "registration_url": "https://cityofvictoria.perfectmind.com/23902/Clients/BookMe4?widgetId=15f6af07-39c5-473e-b053-96653f77a406",
        "scrape_strategy": "perfectmind",
        "automation_status": "active",
        "sync_source_key": "perfectmind_victoria",
        "tags": ["municipal", "multi-activity", "arts", "sports"],
    },
    {
        "source_key": "saanich_day_camps",
        "name": "Saanich Parks, Recreation & Community Services",
        "municipality": "Saanich",
        "venue_names": [
            "Cedar Hill Recreation Centre",
            "G. R. Pearkes Recreation Centre",
            "Gordon Head Recreation Centre",
            "Saanich Commonwealth Place",
        ],
        "primary_url": "https://www.saanich.ca/EN/main/parks-recreation-community/recreation/saanich-day-camps.html",
        "registration_url": "https://anc.ca.apm.activecommunities.com/saanich/activity/search?onlineSiteId=0&activity_select_param=2&viewMode=list",
        "scrape_strategy": "activenet_activity_search",
        "automation_status": "partial",
        "sync_source_key": "saanich_active_communities",
        "tags": ["municipal", "multi-activity", "arts", "sports", "stem"],
    },
    {
        "source_key": "oak_bay_camps",
        "name": "Oak Bay Parks, Recreation & Culture",
        "municipality": "Oak Bay",
        "venue_names": ["Oak Bay Recreation Centre", "Henderson Recreation Centre"],
        "primary_url": "https://www.oakbay.ca/parks-recreation/programs-registration/camps/",
        "registration_url": "https://oakbayrec.perfectmind.com/22950/Store/BookMe4?widgetId=403780fd-76ad-4aaf-9816-c964b90d626d&embed=true",
        "scrape_strategy": "perfectmind",
        "automation_status": "active",
        "sync_source_key": "perfectmind_oak_bay",
        "tags": ["municipal", "multi-activity", "sports", "arts"],
    },
    {
        "source_key": "esquimalt_camps",
        "name": "Esquimalt Parks & Recreation",
        "municipality": "Esquimalt",
        "venue_names": ["Esquimalt Recreation Centre"],
        "primary_url": "https://www.esquimalt.ca/parks-recreation",
        "registration_url": "https://esquimalt.perfectmind.com/22948/Clients/BookMe4BookingPages/Classes?calendarId=e9dde8b8-fd55-4ee0-837e-08323e213b56&widgetId=15f6af07-39c5-473e-b053-96653f77a406&embed=False",
        "scrape_strategy": "perfectmind",
        "automation_status": "active",
        "sync_source_key": "perfectmind_esquimalt",
        "tags": ["municipal", "multi-activity", "childcare"],
    },
    {
        "source_key": "west_shore_parks_recreation_camps",
        "name": "West Shore Parks & Recreation",
        "municipality": "West Shore",
        "venue_names": ["Juan de Fuca Recreation Centre", "West Shore Parks & Recreation"],
        "primary_url": "https://www.wspr.ca/",
        "registration_url": "https://explore.wspr.ca/Westshore/public/category/browse/pro_camp",
        "scrape_strategy": "intelligenz_programs",
        "automation_status": "active",
        "sync_source_key": "west_shore_camps",
        "tags": ["municipal", "multi-activity", "sports", "arts", "licensed"],
    },
    {
        "source_key": "panorama_recreation_camps",
        "name": "Panorama Recreation",
        "municipality": "North Saanich / Sidney",
        "venue_names": ["Panorama Recreation Centre", "Greenglade Community Centre"],
        "primary_url": "https://www.panoramarecreation.ca/",
        "registration_url": "https://panoramarec.perfectmind.com/22938/Clients/BookMe4?widgetId=15f6af07-39c5-473e-b053-96653f77a406",
        "scrape_strategy": "perfectmind",
        "automation_status": "active",
        "sync_source_key": "perfectmind_panorama",
        "tags": ["municipal", "multi-activity", "sports", "arts", "stem"],
    },
    {
        "source_key": "seaparc_camps",
        "name": "SEAPARC Recreation Centre",
        "municipality": "Sooke",
        "venue_names": ["SEAPARC Recreation Centre"],
        "primary_url": "https://www.seaparc.ca/",
        "registration_url": "https://seaparcrecreation.perfectmind.com/22953/Clients/BookMe4?widgetId=15f6af07-39c5-473e-b053-96653f77a406",
        "scrape_strategy": "perfectmind",
        "automation_status": "active",
        "sync_source_key": "perfectmind_sooke",
        "tags": ["municipal", "multi-activity", "spring-break", "summer"],
    },
    {
        "source_key": "uvic_vikes_camps",
        "name": "Vikes Camps at UVic",
        "municipality": "Victoria",
        "venue_names": ["University of Victoria", "CARSA"],
        "primary_url": "https://www.uvic.ca/community-engagement/recreation/child-youth-camps/index.php",
        "registration_url": "https://vikesrec.ca/",
        "scrape_strategy": "provider_page",
        "automation_status": "partial",
        "sync_source_key": "uvic_vikesrec",
        "tags": ["sports", "outdoor", "climbing", "swimming"],
    },
    {
        "source_key": "science_venture_uvic",
        "name": "Science Venture",
        "municipality": "Victoria",
        "venue_names": ["University of Victoria", "Swan Lake Nature Sanctuary"],
        "primary_url": "https://www.scienceventure.ca/camps",
        "registration_url": "https://www.scienceventure.ca/camps",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["stem", "science", "coding", "nature"],
    },
    {
        "source_key": "swan_lake_science_venture",
        "name": "Swan Lake Nature Sanctuary / Science Venture",
        "municipality": "Saanich",
        "venue_names": ["Swan Lake Nature Sanctuary"],
        "primary_url": "https://www.swanlake.bc.ca/community-programs/",
        "registration_url": "https://www.scienceventure.ca/camps/specialty",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["nature", "stem", "outdoor"],
    },
    {
        "source_key": "ymca_camp_thunderbird",
        "name": "YMCA-YWCA Camp Thunderbird",
        "municipality": "Sooke Hills",
        "venue_names": ["Camp Thunderbird"],
        "primary_url": "https://vancouverislandy.com/program-services/outdoor-education-overview/summer-camp-overview/",
        "registration_url": "https://vancouverislandy.com/program-services/outdoor-education-overview/summer-camp-overview/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["outdoor", "overnight", "day-camp", "bus"],
    },
    {
        "source_key": "braefoot_camps",
        "name": "Braefoot Community Association",
        "municipality": "Saanich",
        "venue_names": ["Braefoot Park", "Braefoot Community Association"],
        "primary_url": "https://www.braefoot.ca/summer-camps",
        "registration_url": "https://www.braefoot.ca/summer-camps",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["multi-activity", "sports", "pro-d", "school-break"],
    },
    {
        "source_key": "pedalheads_victoria",
        "name": "Pedalheads",
        "municipality": "Victoria",
        "venue_names": ["Multiple Victoria locations"],
        "primary_url": "https://www.pedalheads.com/",
        "registration_url": "https://www.pedalheads.com/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["cycling", "bike", "sports"],
    },
    {
        "source_key": "wildplay_victoria",
        "name": "WildPlay Victoria",
        "municipality": "Colwood",
        "venue_names": ["WildPlay Victoria"],
        "primary_url": "https://www.wildplay.com/victoria/",
        "registration_url": "https://www.wildplay.com/victoria/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["outdoor", "adventure"],
    },
    {
        "source_key": "gns_camps",
        "name": "Glenlyon Norfolk School Camps",
        "municipality": "Victoria",
        "venue_names": ["GNS Beach Campus"],
        "primary_url": "https://www.mygns.ca/community/camps/gns-summer-camps/",
        "registration_url": "https://gnscamps.campbrainregistration.com/",
        "scrape_strategy": "campbrain",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["school", "sports", "arts", "outdoor", "stem"],
    },
    {
        "source_key": "smus_camps",
        "name": "St. Michaels University School Camps",
        "municipality": "Victoria",
        "venue_names": ["SMUS Richmond Road Campus", "SMUS Junior School"],
        "primary_url": "https://www.smus.ca/camps",
        "registration_url": "https://www.smus.ca/camps",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["school", "sports", "arts", "stem", "overnight"],
    },
    {
        "source_key": "st_margarets_camps",
        "name": "St. Margaret's School Camps",
        "municipality": "Saanich",
        "venue_names": ["St. Margaret's School"],
        "primary_url": "https://www.stmarg.ca/student-life/camps",
        "registration_url": "https://www.stmarg.ca/student-life/camps",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["school", "sports", "arts", "stem"],
    },
    {
        "source_key": "kaleidoscope_theatre_camps",
        "name": "Kaleidoscope Theatre",
        "municipality": "Victoria / Saanich",
        "venue_names": ["Kaleidoscope Arts Centre", "GNS", "Saanich Recreation Centres"],
        "primary_url": "https://kaleidoscope.bc.ca/programs-types/summer-camps/",
        "registration_url": "https://kaleidoscope.bc.ca/programs-types/summer-camps/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["theatre", "arts", "pro-d", "spring-break"],
    },
    {
        "source_key": "aggv_studio_camps",
        "name": "Art Gallery of Greater Victoria",
        "municipality": "Victoria",
        "venue_names": ["Art Gallery of Greater Victoria"],
        "primary_url": "https://aggv.ca/events/aggv-studio-summer-registration-is-open/",
        "registration_url": "https://aggv.ca/events/aggv-studio-summer-registration-is-open/",
        "scrape_strategy": "shopify_or_provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["arts", "gallery"],
    },
    {
        "source_key": "paint_box_victoria",
        "name": "The Paint Box",
        "municipality": "Victoria",
        "venue_names": ["The Paint Box"],
        "primary_url": "https://www.thepaintbox-victoria.com/",
        "registration_url": "https://www.thepaintbox-victoria.com/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["arts"],
    },
    {
        "source_key": "mctavish_academy_art",
        "name": "McTavish Academy of Art",
        "municipality": "North Saanich",
        "venue_names": ["McTavish Academy of Art"],
        "primary_url": "https://mctavishacademy.ca/",
        "registration_url": "https://mctavishacademy.ca/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["arts", "nature"],
    },
    {
        "source_key": "kids_klub",
        "name": "Kids Klub",
        "municipality": "Saanich",
        "venue_names": ["Kids Klub"],
        "primary_url": "https://www.kidsklub.ca/summer-day-camps",
        "registration_url": "https://www.kidsklub.ca/summer-day-camps",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["licensed", "childcare", "multi-activity"],
    },
    {
        "source_key": "birdhouse_creative_studio",
        "name": "Birdhouse Creative Studio",
        "municipality": "Langford",
        "venue_names": ["Birdhouse Creative Studio"],
        "primary_url": "https://www.birdhousecreativestudio.com/",
        "registration_url": "https://www.birdhousecreativestudio.com/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["arts", "creative"],
    },
    {
        "source_key": "western_educational_adventures",
        "name": "Western Educational Adventures",
        "municipality": "Greater Victoria",
        "venue_names": ["Greater Victoria"],
        "primary_url": "https://www.westernadventures.ca/",
        "registration_url": "https://www.westernadventures.ca/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["outdoor", "adventure", "overnight"],
    },
    {
        "source_key": "victoria_city_rowing_club",
        "name": "Victoria City Rowing Club",
        "municipality": "Saanich",
        "venue_names": ["Elk Lake"],
        "primary_url": "https://www.vcrc.bc.ca/",
        "registration_url": "https://www.vcrc.bc.ca/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["rowing", "sports", "water"],
    },
    {
        "source_key": "byte_camp_victoria",
        "name": "Byte Camp",
        "municipality": "Victoria / Saanich / West Shore",
        "venue_names": ["Byte Camp Victoria HQ", "Cedar Hill Recreation Centre", "Juan de Fuca Recreation Centre", "Esquimalt Recreation Centre"],
        "primary_url": "https://bytecamp.ca/calendar/",
        "registration_url": "https://bytecamp.ca/calendar/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["coding", "animation", "stem", "arts"],
    },
    {
        "source_key": "royal_victoria_yacht_club",
        "name": "Royal Victoria Yacht Club",
        "municipality": "Oak Bay",
        "venue_names": ["Royal Victoria Yacht Club"],
        "primary_url": "https://rvyc.bc.ca/On_the_Water/Sail_Programs",
        "registration_url": "https://rvyc.bc.ca/On_the_Water/Sail_Programs",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["sailing", "water", "sports"],
    },
    {
        "source_key": "sidney_north_saanich_yacht_club",
        "name": "Sidney North Saanich Yacht Club",
        "municipality": "North Saanich / Sidney",
        "venue_names": ["Sidney North Saanich Yacht Club"],
        "primary_url": "https://snsyc.ca/",
        "registration_url": "https://snsyc.ca/",
        "scrape_strategy": "wild_apricot_or_provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["sailing", "water", "sports"],
    },
    {
        "source_key": "victoria_gymnastics",
        "name": "Victoria Gymnastics",
        "municipality": "Victoria",
        "venue_names": ["Victoria Gymnastics"],
        "primary_url": "https://www.victoriagymnastics.com/",
        "registration_url": "https://www.victoriagymnastics.com/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["gymnastics", "sports"],
    },
    {
        "source_key": "falcon_gymnastics",
        "name": "Falcon Gymnastics",
        "municipality": "Victoria",
        "venue_names": ["Falcon Gymnastics"],
        "primary_url": "https://falcongymnastics.com/",
        "registration_url": "https://falcongymnastics.com/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["gymnastics", "sports"],
    },
    {
        "source_key": "inspire_sports_victoria",
        "name": "Inspire Sports Victoria",
        "municipality": "Victoria",
        "venue_names": ["Inspire Sports Victoria"],
        "primary_url": "https://www.inspiresportsvictoria.com/",
        "registration_url": "https://www.inspiresportsvictoria.com/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["gymnastics", "sports"],
    },
    {
        "source_key": "victoria_conservatory_music",
        "name": "Victoria Conservatory of Music",
        "municipality": "Victoria",
        "venue_names": ["Victoria Conservatory of Music"],
        "primary_url": "https://vcm.bc.ca/",
        "registration_url": "https://vcm.bc.ca/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["music", "theatre", "arts"],
    },
    {
        "source_key": "ballet_victoria_conservatory",
        "name": "Ballet Victoria Conservatory",
        "municipality": "Victoria",
        "venue_names": ["Ballet Victoria Conservatory"],
        "primary_url": "https://www.bvconservatory.org/",
        "registration_url": "https://www.bvconservatory.org/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["dance", "arts"],
    },
    {
        "source_key": "stages_dance",
        "name": "STAGES Dance",
        "municipality": "Saanich",
        "venue_names": ["STAGES Dance"],
        "primary_url": "https://www.stagesdance.com/",
        "registration_url": "https://www.stagesdance.com/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["dance", "arts"],
    },
    {
        "source_key": "victoria_beach_volleyball",
        "name": "Victoria Beach Volleyball Club",
        "municipality": "Victoria",
        "venue_names": ["Vic High Beach Courts"],
        "primary_url": "https://www.victoriabeachvolleyballclub.com/",
        "registration_url": "https://www.victoriabeachvolleyballclub.com/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["volleyball", "sports"],
    },
    {
        "source_key": "pacific_fc_camps",
        "name": "Pacific FC Camps & Clinics",
        "municipality": "Langford",
        "venue_names": ["Starlight Stadium"],
        "primary_url": "https://pacificfc.org/camps-clinics/",
        "registration_url": "https://pacificfc.org/camps-clinics/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["soccer", "sports"],
    },
    {
        "source_key": "jumpshot_basketball",
        "name": "Jumpshot Basketball",
        "municipality": "Victoria",
        "venue_names": ["Victoria-area gyms"],
        "primary_url": "https://www.jumpshotbasketball.org/",
        "registration_url": "https://www.jumpshotbasketball.org/",
        "scrape_strategy": "provider_page",
        "automation_status": "planned",
        "sync_source_key": "",
        "tags": ["basketball", "sports"],
    },
]
