TARGET_SPORTS = [
    "hockey",
    "soccer",
    "squash",
    "pickleball",
    "badminton",
]


def venue(
    municipality,
    venue_name,
    source_system,
    source_url,
    primary_method,
    *,
    fallback_method=None,
    connector=None,
    fallback_connector=None,
    connector_confirmed=False,
    evidence_url=None,
    status="missing",
    priority="medium",
    sports=None,
    automation_ready=False,
    refresh_group="manual_review",
    notes="",
):
    return {
        "municipality": municipality,
        "venue_name": venue_name,
        "source_system": source_system,
        "source_url": source_url,
        "primary_method": primary_method,
        "fallback_method": fallback_method,
        "connector": connector or primary_method,
        "fallback_connector": fallback_connector or fallback_method,
        "connector_confirmed": connector_confirmed,
        "evidence_url": evidence_url,
        "preferred_method": primary_method,
        "status": status,
        "priority": priority,
        "sports": sports or [],
        "automation_ready": automation_ready,
        "refresh_group": refresh_group,
        "sync_methods": [method for method in [primary_method, fallback_method] if method],
        "notes": notes,
    }


VENUE_REGISTRY = [
    venue(
        "Saanich",
        "Cedar Hill Recreation Centre",
        "Active Communities",
        "https://anc.ca.apm.activecommunities.com/saanich/calendars",
        "api",
        connector="active_communities_api",
        connector_confirmed=True,
        status="covered",
        priority="high",
        sports=["pickleball", "badminton"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Structured Active Communities calendar API.",
    ),
    venue(
        "Saanich",
        "G. R. Pearkes Recreation Centre",
        "Active Communities",
        "https://anc.ca.apm.activecommunities.com/saanich/calendars",
        "api",
        fallback_method="pdf",
        connector="active_communities_api",
        fallback_connector="schedule_pdf",
        connector_confirmed=True,
        status="covered",
        priority="high",
        sports=["hockey"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Active Communities remains primary. The weekly sync now adds a Pearkes skating PDF fallback for public skating, adult figure skate, and late-month Stick & Puck one-off rows that the API can miss.",
    ),
    venue(
        "Saanich",
        "Saanich Commonwealth Place",
        "Active Communities",
        "https://anc.ca.apm.activecommunities.com/saanich/calendars",
        "api",
        connector="active_communities_api",
        connector_confirmed=True,
        status="covered",
        priority="high",
        sports=["pickleball", "badminton", "squash"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Structured Active Communities calendar API.",
    ),
    venue(
        "Saanich",
        "Gordon Head Recreation Centre",
        "Active Communities",
        "https://anc.ca.apm.activecommunities.com/saanich/calendars",
        "api",
        connector="active_communities_api",
        connector_confirmed=True,
        evidence_url="https://anc.ca.apm.activecommunities.com/saanich/rest/onlinecalendar/filters?locale=en-US",
        status="covered",
        priority="high",
        sports=["fitness", "kids", "community"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Structured Active Communities center ID 98. Current public Saanich filter payload exposes Gordon Head Recreation Centre on calendars 2, 5, 8, and 10, and the scraper now includes it in the Saanich center set.",
    ),
    venue(
        "Saanich",
        "Gordon Head Middle School",
        "Active Communities",
        "https://anc.ca.apm.activecommunities.com/saanich/calendars",
        "api",
        connector="active_communities_api",
        connector_confirmed=True,
        status="covered",
        priority="medium",
        sports=["soccer", "pickleball", "badminton"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Appears in Saanich API feed.",
    ),
    venue(
        "Saanich",
        "Colquitz Middle School",
        "Active Communities",
        "https://anc.ca.apm.activecommunities.com/saanich/calendars",
        "api",
        connector="active_communities_api",
        connector_confirmed=True,
        status="covered",
        priority="low",
        sports=["soccer", "pickleball", "badminton"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Appears in Saanich API feed.",
    ),
    venue(
        "Victoria",
        "Crystal Pool and Fitness Centre",
        "PerfectMind via Victoria wrapper",
        "https://www.victoria.ca/parks-recreation/recreation/activities-registration",
        "api",
        connector="victoria_wrapper_api",
        connector_confirmed=True,
        status="covered",
        priority="high",
        sports=["pickleball", "badminton"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Currently the only Victoria venue landing in the DB; lower relevance for target pickup sports.",
    ),
    venue(
        "Victoria",
        "Royal Athletic Park",
        "Victoria site / unknown backing",
        "https://www.victoria.ca/parks-recreation/recreation/royal-athletic-park",
        "html",
        fallback_method="pdf",
        connector="static_html",
        fallback_connector="schedule_pdf",
        status="not_target",
        priority="low",
        sports=["soccer"],
        automation_ready=False,
        refresh_group="not_target",
        notes="Official City pages describe team practice/play and permit use, not a recurring public drop-in schedule.",
    ),
    venue(
        "Victoria",
        "Quadra Village Community Centre",
        "Squarespace site with Calendar.online API",
        "https://api.calendar.online/calendar?capabilityId=3014533ec3d996e84c39",
        "api",
        fallback_method="pdf",
        connector="calendar_online_api",
        fallback_connector="schedule_pdf",
        connector_confirmed=True,
        evidence_url="https://www.qvcc.ca/calendar-1",
        status="covered",
        priority="low",
        sports=["community", "fitness", "kids"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Sync now uses Quadra's public Calendar.online API discovered from the /calendar-1 iframe embed, with PDF fallback only for guide-style assets not present in the feed.",
    ),
    venue(
        "Victoria",
        "Burnside Gorge Community Centre",
        "WordPress site with Google Calendar Events plugin",
        "https://burnsidegorge.ca/recreation-special-events/",
        "html",
        fallback_method="pdf",
        connector="wordpress_google_calendar_html",
        fallback_connector="schedule_pdf",
        connector_confirmed=True,
        evidence_url="https://burnsidegorge.ca/recreation-special-events/",
        status="covered_partial",
        priority="low",
        sports=["community", "fitness", "youth"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Current sync ingests explicit Burnside program pages directly, including Health and Wellness, Youth Drop-In, and KATS Tennis. The site exposes a Google Calendar plugin shell, but current timed public activity data still mainly lives on the explicit program pages.",
    ),
    venue(
        "Victoria",
        "Fairfield Community Place",
        "RecDesk via Fairfield Gonzales Community Association",
        "https://fgca.recdesk.com/Community/Calendar",
        "api",
        fallback_method="pdf",
        connector="recdesk_calendar_api",
        fallback_connector="schedule_pdf",
        connector_confirmed=True,
        evidence_url="https://fgca.recdesk.com/Community/Calendar",
        status="covered",
        priority="low",
        sports=["community", "fitness", "kids"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Public RecDesk calendar JSON feed is live and now ingested directly, with PDF fallback only if Fairfield adds extra guide-only content.",
    ),
    venue(
        "Victoria",
        "Fernwood Community Centre",
        "WordPress site with EventON calendar",
        "https://fernwoodnrg.ca/events-directory/calendar/",
        "html",
        fallback_method="pdf",
        connector="eventon_wp_rest_api",
        fallback_connector="image_guide",
        connector_confirmed=True,
        evidence_url="https://fernwoodnrg.ca/events-directory/calendar/",
        status="covered",
        priority="low",
        sports=["community", "fitness", "kids"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Sync now uses Fernwood's public WordPress ajde_events REST feed for EventON events, with guide/image fallback only if the feed misses schedule-only content.",
    ),
    venue(
        "Victoria",
        "James Bay Community School Centre",
        "WordPress site with public events page",
        "https://www.jamesbaycentre.ca/jb-events/",
        "html",
        fallback_method="pdf",
        connector="wordpress_events_html",
        fallback_connector="image_guide",
        connector_confirmed=True,
        evidence_url="https://www.jamesbaycentre.ca/jb-events/",
        status="covered_partial",
        priority="low",
        sports=["community", "fitness", "kids"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Sync now ingests the live /jb-events page plus structured 55+ meals order-form pages. Remaining gap is class/program timing that is exposed more fully in Amilia than on the WordPress pages.",
    ),
    venue(
        "Victoria",
        "Oaklands Community Centre",
        "RecDesk via Oaklands Community Association",
        "https://oca.recdesk.com/Community/Calendar",
        "api",
        fallback_method="pdf",
        connector="recdesk_calendar_api",
        fallback_connector="schedule_pdf",
        connector_confirmed=True,
        evidence_url="https://oca.recdesk.com/Community/Calendar",
        status="covered",
        priority="low",
        sports=["community", "fitness", "youth"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Public RecDesk calendar JSON feed is live and now ingested directly for classes and drop-ins.",
    ),
    venue(
        "Victoria",
        "Victoria West Community Centre",
        "RecDesk via Victoria West Community Association",
        "https://victoriawest.recdesk.com/Community/Calendar",
        "api",
        fallback_method="pdf",
        connector="recdesk_calendar_api",
        fallback_connector="schedule_pdf",
        connector_confirmed=True,
        evidence_url="https://victoriawest.recdesk.com/Community/Calendar",
        status="covered",
        priority="low",
        sports=["community", "fitness", "youth"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Public RecDesk calendar JSON feed is live and now ingested directly for classes and drop-ins.",
    ),
    venue(
        "Victoria",
        "James Bay New Horizons",
        "Weebly monthly calendar PDF",
        "https://jamesbaynewhorizons.weebly.com/monthly-calendar.html",
        "pdf",
        fallback_method="html",
        connector="weebly_pdf_calendar",
        fallback_connector="weebly_pages_html",
        connector_confirmed=True,
        evidence_url="https://jamesbaynewhorizons.weebly.com/monthly-calendar.html",
        status="covered_partial",
        priority="low",
        sports=["community", "fitness", "seniors"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Sync now ingests the live JBNH monthly calendar PDF directly. Upcoming poster-style events remain a secondary HTML/image fallback.",
    ),
    venue(
        "Victoria",
        "Cook Street Village Activity Centre",
        "Static site with linked program PDFs",
        "https://cookstreetvillageactivitycentre.com/calendar-and-programs",
        "pdf",
        fallback_method="html",
        connector="static_program_pdfs",
        fallback_connector="static_html",
        connector_confirmed=True,
        evidence_url="https://cookstreetvillageactivitycentre.com/calendar-and-programs",
        status="covered_partial",
        priority="low",
        sports=["community", "fitness", "seniors"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Sync now uses the live Cook Street monthly calendar PDF. The linked guide and poster files remain fallback sources for items that need richer metadata.",
    ),
    venue(
        "Victoria",
        "Victoria Silver Threads Seniors Centre",
        "RecDesk via Silver Threads",
        "https://silverthreads.recdesk.com/Community/Calendar",
        "api",
        fallback_method="pdf",
        connector="recdesk_calendar_api",
        fallback_connector="schedule_pdf",
        connector_confirmed=True,
        evidence_url="https://silverthreads.recdesk.com/Community/Calendar",
        status="covered",
        priority="low",
        sports=["community", "fitness", "seniors", "pickleball", "badminton"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Public RecDesk calendar feed is live; sync splits Victoria and Saanich rows by title, with PDF fallback available for drop-in grids.",
    ),
    venue(
        "Saanich",
        "Saanich Silver Threads Seniors Centre",
        "RecDesk via Silver Threads",
        "https://silverthreads.recdesk.com/Community/Calendar",
        "api",
        fallback_method="pdf",
        connector="recdesk_calendar_api",
        fallback_connector="schedule_pdf",
        connector_confirmed=True,
        evidence_url="https://silverthreads.recdesk.com/Community/Calendar",
        status="covered",
        priority="low",
        sports=["community", "fitness", "seniors"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Silver Threads RecDesk feed includes Saanich-centre rows; sync routes them here by title.",
    ),
    venue(
        "UVic",
        "CARSA / Vikes Recreation",
        "Vikes Recreation public schedule",
        "https://www.vikesrec.ca/schedule",
        "html",
        fallback_method="html",
        connector="vikesrec_schedule_html",
        fallback_connector="activeliving_program_search_public",
        connector_confirmed=True,
        evidence_url="https://www.vikesrec.ca/drop-in",
        status="covered_partial",
        priority="high",
        sports=["pickleball", "badminton", "basketball", "volleyball", "fitness", "yoga"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Public UVic Vikes Recreation schedule pages expose drop-in, group fitness, registered fitness, yoga, and pickleball timings without login. Booking/register links point into activeliving.uvic.ca, but the weekly schedule HTML is publicly readable and suitable for recurring syncs. Squash still appears booking-only from the public site and is not yet ingested as timed events.",
    ),
    venue(
        "Esquimalt",
        "Esquimalt Recreation Centre",
        "PerfectMind",
        "https://www.esquimalt.ca/schedules",
        "widget",
        connector="perfectmind_widget_v2",
        connector_confirmed=True,
        status="covered",
        priority="high",
        sports=["pickleball", "badminton", "soccer"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Esquimalt schedules page now seeds live PerfectMind links for pool, waterfit, sports, fitness, youth, and 50+ drop-ins. Cleanup is now mainly classification/noise reduction, not source discovery.",
    ),
    venue(
        "Esquimalt",
        "Archie Browning Sports Centre",
        "PerfectMind",
        "https://www.esquimalt.ca/arena",
        "widget",
        connector="perfectmind_widget_v2",
        connector_confirmed=True,
        status="covered",
        priority="high",
        sports=["hockey"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Appears in Esquimalt feed.",
    ),
    venue(
        "Esquimalt",
        "L'ecole Brodeur School",
        "PerfectMind",
        "https://www.esquimalt.ca/schedules",
        "widget",
        connector="perfectmind_widget_v2",
        connector_confirmed=True,
        status="covered",
        priority="medium",
        sports=["soccer", "badminton"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Appears in Esquimalt feed.",
    ),
    venue(
        "Panorama",
        "Panorama Recreation Centre",
        "PerfectMind",
        "https://www.panoramarecreation.ca/activities-registration/drop-schedules",
        "widget",
        connector="perfectmind_widget_v2",
        connector_confirmed=True,
        status="covered",
        priority="high",
        sports=["pickleball", "badminton", "squash", "hockey", "soccer"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Strong target-sport venue for pickleball, squash, badminton, and hockey-adjacent court sports.",
    ),
    venue(
        "Panorama",
        "Greenglade Community Centre",
        "PerfectMind",
        "https://www.panoramarecreation.ca/activities-registration/drop-schedules",
        "widget",
        connector="perfectmind_widget_v2",
        connector_confirmed=True,
        status="covered",
        priority="high",
        sports=["pickleball", "badminton"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Strong target-sport venue for pickleball and badminton-style community court play.",
    ),
    venue(
        "Panorama",
        "Centennial Park",
        "PerfectMind",
        "https://www.panoramarecreation.ca/activities-registration/drop-schedules",
        "widget",
        connector="perfectmind_widget_v2",
        connector_confirmed=True,
        status="covered",
        priority="medium",
        sports=["soccer", "pickleball"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Direct V2 extraction works.",
    ),
    venue(
        "Panorama",
        "North Saanich Middle School",
        "PerfectMind",
        "https://www.panoramarecreation.ca/activities-registration/drop-schedules",
        "widget",
        connector="perfectmind_widget_v2",
        connector_confirmed=True,
        status="covered",
        priority="medium",
        sports=["soccer", "pickleball", "badminton"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Direct V2 extraction works.",
    ),
    venue(
        "Oak Bay",
        "Oak Bay Recreation Centre",
        "PerfectMind",
        "https://oakbayrec.perfectmind.com/22950/Store/BookMe4?widgetId=403780fd-76ad-4aaf-9816-c964b90d626d&embed=true",
        "widget",
        fallback_method="pdf",
        connector="perfectmind_widget_v2",
        fallback_connector="schedule_pdf",
        connector_confirmed=True,
        status="covered",
        priority="high",
        sports=["hockey", "pickleball", "badminton", "squash"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Oak Bay's public drop-in page is currently a schedule hub for aquatics, arena, racquet sports, and fitness PDFs; those schedule families are now wired into weekly sync alongside PerfectMind hockey/duffer rows.",
    ),
    venue(
        "Oak Bay",
        "Henderson Recreation Centre",
        "Oak Bay PDF schedule",
        "https://www.oakbay.ca/wp-content/uploads/2026/03/RacquetSports-Drop-in-Schedule-Spring-2026.pdf",
        "pdf",
        fallback_method="pdf",
        connector="oakbay_pdf_schedule",
        fallback_connector="oakbay_pdf_schedule",
        connector_confirmed=True,
        evidence_url="https://www.oakbay.ca/wp-content/uploads/2026/03/RacquetSports-Drop-in-Schedule-Spring-2026.pdf",
        status="covered",
        priority="high",
        sports=["pickleball", "badminton", "squash"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Current Spring 2026 racquet sports PDF now feeds Henderson pickleball and badminton sessions.",
    ),
    venue(
        "Oak Bay",
        "Monterey Recreation Centre",
        "Oak Bay group fitness PDF / PerfectMind",
        "https://www.oakbay.ca/wp-content/uploads/2026/03/Fitness-Drop-in-Schedule-March-30-April-30-2026.pdf",
        "pdf",
        fallback_method="widget",
        connector="oakbay_group_fitness_pdf",
        fallback_connector="perfectmind_or_schedule_pdf",
        connector_confirmed=True,
        evidence_url="https://www.oakbay.ca/wp-content/uploads/2026/03/Fitness-Drop-in-Schedule-March-30-April-30-2026.pdf",
        status="covered",
        priority="low",
        sports=["community", "fitness", "seniors"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Current Oak Bay group fitness PDF provides live Monterey class times; PerfectMind remains a secondary path for registered classes.",
    ),
    venue(
        "Oak Bay",
        "Windsor Pavilion",
        "Oak Bay site / schedule PDFs",
        "https://www.oakbay.ca/parks-recreation/drop-in-schedules/",
        "pdf",
        fallback_method="html",
        connector="schedule_pdf",
        fallback_connector="static_html",
        connector_confirmed=True,
        evidence_url="https://www.oakbay.ca/event/personal-emergency-preparedness-information-session-obep/",
        status="not_target",
        priority="low",
        sports=["community", "fitness", "seniors"],
        automation_ready=False,
        refresh_group="not_target",
        notes="Windsor Pavilion is a real Oak Bay venue, but current public sources show general city events rather than a distinct recurring drop-in/program schedule feed.",
    ),
    venue(
        "Oak Bay",
        "Oak Bay Indoor Sports Field",
        "Oak Bay group fitness PDF",
        "https://www.oakbay.ca/wp-content/uploads/2026/03/Fitness-Drop-in-Schedule-March-30-April-30-2026.pdf",
        "pdf",
        connector="oakbay_group_fitness_pdf",
        connector_confirmed=True,
        evidence_url="https://www.oakbay.ca/wp-content/uploads/2026/03/Fitness-Drop-in-Schedule-March-30-April-30-2026.pdf",
        status="covered",
        priority="low",
        sports=["fitness"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Current Oak Bay group fitness PDF includes Indoor Bootcamp at the Oak Bay Indoor Sports Field.",
    ),
    venue(
        "Oak Bay",
        "Neighbourhood Learning Centre",
        "Oak Bay group fitness PDF / facility page",
        "https://www.oakbay.ca/wp-content/uploads/2026/03/Fitness-Drop-in-Schedule-March-30-April-30-2026.pdf",
        "pdf",
        fallback_method="html",
        connector="oakbay_group_fitness_pdf",
        fallback_connector="oakbay_facility_html",
        connector_confirmed=True,
        evidence_url="https://www.oakbay.ca/wp-content/uploads/2026/03/Fitness-Drop-in-Schedule-March-30-April-30-2026.pdf",
        status="covered",
        priority="low",
        sports=["community", "fitness", "youth"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Current Oak Bay group fitness PDF provides live NLC class times; facility page remains useful as a fallback context source.",
    ),
    venue(
        "West Shore",
        "Juan de Fuca Rec Centre",
        "Explore WSPR",
        "https://explore.wspr.ca/Westshore/public/category/browse/dropin",
        "html",
        fallback_method="pdf",
        connector="wspr_public_html",
        fallback_connector="schedule_pdf",
        connector_confirmed=True,
        status="covered",
        priority="high",
        sports=["pickleball", "badminton", "basketball", "soccer", "hockey"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Recursive WSPR discovery now covers sports and weight/fitness branches, weekly ClassGrid timetable pages, and ClassSchedule pages used by West Shore pool categories. Daily-hours-only content is monitored separately but is not modeled as bookable events.",
    ),
    venue(
        "West Shore",
        "Juan de Fuca Outdoor Facilities",
        "Explore WSPR",
        "https://explore.wspr.ca/Westshore/public/booking/items/PICKLEBALLCOURTSONLINE",
        "html",
        connector="wspr_booking_grid",
        connector_confirmed=True,
        status="covered",
        priority="medium",
        sports=["pickleball"],
        automation_ready=True,
        refresh_group="scheduled_sync",
        notes="Outdoor pickleball courts 5 and 6 drop-in availability is now scraped from the public booking grid.",
    ),
    venue(
        "West Shore",
        "The Q Centre Arena",
        "WSPR site / unknown backing",
        "https://www.wspr.ca/about-us/location",
        "html",
        fallback_method="pdf",
        connector="static_html",
        fallback_connector="schedule_pdf",
        status="not_target",
        priority="low",
        sports=["hockey"],
        automation_ready=False,
        refresh_group="not_target",
        notes="Excluded from ClubHub venue discovery per product scope; not an active public community venue target.",
    ),
]
