VENUE_REGISTRY = [
    {
        "municipality": "Saanich",
        "venue_name": "Cedar Hill Recreation Centre",
        "source_system": "Active Communities",
        "source_url": "https://anc.ca.apm.activecommunities.com/saanich/calendars",
        "primary_method": "api",
        "fallback_method": None,
        "status": "covered",
        "priority": "high",
        "notes": "Structured Active Communities calendar API.",
    },
    {
        "municipality": "Saanich",
        "venue_name": "G. R. Pearkes Recreation Centre",
        "source_system": "Active Communities",
        "source_url": "https://anc.ca.apm.activecommunities.com/saanich/calendars",
        "primary_method": "api",
        "fallback_method": "pdf",
        "status": "covered_partial",
        "priority": "high",
        "notes": "API coverage is good; skating/hockey schedule pages may still require PDF fallback.",
    },
    {
        "municipality": "Saanich",
        "venue_name": "Saanich Commonwealth Place",
        "source_system": "Active Communities",
        "source_url": "https://anc.ca.apm.activecommunities.com/saanich/calendars",
        "primary_method": "api",
        "fallback_method": None,
        "status": "covered",
        "priority": "high",
        "notes": "Structured Active Communities calendar API.",
    },
    {
        "municipality": "Saanich",
        "venue_name": "Gordon Head Middle School",
        "source_system": "Active Communities",
        "source_url": "https://anc.ca.apm.activecommunities.com/saanich/calendars",
        "primary_method": "api",
        "fallback_method": None,
        "status": "covered",
        "priority": "medium",
        "notes": "Appears in Saanich API feed.",
    },
    {
        "municipality": "Saanich",
        "venue_name": "Colquitz Middle School",
        "source_system": "Active Communities",
        "source_url": "https://anc.ca.apm.activecommunities.com/saanich/calendars",
        "primary_method": "api",
        "fallback_method": None,
        "status": "covered",
        "priority": "low",
        "notes": "Appears in Saanich API feed.",
    },
    {
        "municipality": "Victoria",
        "venue_name": "Crystal Pool and Fitness Centre",
        "source_system": "PerfectMind via Victoria wrapper",
        "source_url": "https://www.victoria.ca/parks-recreation/recreation/activities-registration",
        "primary_method": "api",
        "fallback_method": None,
        "status": "covered",
        "priority": "high",
        "notes": "Currently the only Victoria venue landing in the DB; lower relevance for target pickup sports.",
    },
    {
        "municipality": "Victoria",
        "venue_name": "Royal Athletic Park",
        "source_system": "Victoria site / unknown backing",
        "source_url": "https://www.victoria.ca/parks-recreation/recreation/royal-athletic-park",
        "primary_method": "html",
        "fallback_method": "pdf",
        "status": "missing",
        "priority": "low",
        "notes": "Deprioritized unless it exposes recurring pickup-style soccer or similar drop-in sport.",
    },
    {
        "municipality": "Victoria",
        "venue_name": "Community & Seniors Centres",
        "source_system": "Victoria site / unknown backing",
        "source_url": "https://www.victoria.ca/parks-recreation/recreation/community-seniors-centres",
        "primary_method": "html",
        "fallback_method": "pdf",
        "status": "missing",
        "priority": "medium",
        "notes": "Check only for target sports like badminton, pickleball, squash, or indoor soccer.",
    },
    {
        "municipality": "Esquimalt",
        "venue_name": "Esquimalt Recreation Centre",
        "source_system": "PerfectMind",
        "source_url": "https://www.esquimalt.ca/schedules",
        "primary_method": "widget",
        "fallback_method": None,
        "status": "covered_partial",
        "priority": "high",
        "notes": "Sports data covered; cleanup should focus on target sports and de-emphasize non-sport noise.",
    },
    {
        "municipality": "Esquimalt",
        "venue_name": "Archie Browning Sports Centre",
        "source_system": "PerfectMind",
        "source_url": "https://www.esquimalt.ca/arena",
        "primary_method": "widget",
        "fallback_method": None,
        "status": "covered",
        "priority": "high",
        "notes": "Appears in Esquimalt feed.",
    },
    {
        "municipality": "Esquimalt",
        "venue_name": "L'ecole Brodeur School",
        "source_system": "PerfectMind",
        "source_url": "https://www.esquimalt.ca/schedules",
        "primary_method": "widget",
        "fallback_method": None,
        "status": "covered",
        "priority": "medium",
        "notes": "Appears in Esquimalt feed.",
    },
    {
        "municipality": "Panorama",
        "venue_name": "Panorama Recreation Centre",
        "source_system": "PerfectMind",
        "source_url": "https://www.panoramarecreation.ca/activities-registration/drop-schedules",
        "primary_method": "widget",
        "fallback_method": None,
        "status": "covered",
        "priority": "high",
        "notes": "Strong target-sport venue for pickleball, squash, badminton, and hockey-adjacent court sports.",
    },
    {
        "municipality": "Panorama",
        "venue_name": "Greenglade Community Centre",
        "source_system": "PerfectMind",
        "source_url": "https://www.panoramarecreation.ca/activities-registration/drop-schedules",
        "primary_method": "widget",
        "fallback_method": None,
        "status": "covered",
        "priority": "high",
        "notes": "Strong target-sport venue for pickleball and badminton-style community court play.",
    },
    {
        "municipality": "Panorama",
        "venue_name": "Centennial Park",
        "source_system": "PerfectMind",
        "source_url": "https://www.panoramarecreation.ca/activities-registration/drop-schedules",
        "primary_method": "widget",
        "fallback_method": None,
        "status": "covered",
        "priority": "medium",
        "notes": "Direct V2 extraction works.",
    },
    {
        "municipality": "Panorama",
        "venue_name": "North Saanich Middle School",
        "source_system": "PerfectMind",
        "source_url": "https://www.panoramarecreation.ca/activities-registration/drop-schedules",
        "primary_method": "widget",
        "fallback_method": None,
        "status": "covered",
        "priority": "medium",
        "notes": "Direct V2 extraction works.",
    },
    {
        "municipality": "Oak Bay",
        "venue_name": "Oak Bay Recreation Centre",
        "source_system": "PerfectMind",
        "source_url": "https://oakbayrec.perfectmind.com/22950/Store/BookMe4?widgetId=403780fd-76ad-4aaf-9816-c964b90d626d&embed=true",
        "primary_method": "widget",
        "fallback_method": "pdf",
        "status": "covered_partial",
        "priority": "high",
        "notes": "Hockey/duffer is covered; next target sports here are pickleball, badminton, and squash if publicly scheduled.",
    },
    {
        "municipality": "Oak Bay",
        "venue_name": "Henderson Recreation Centre",
        "source_system": "Oak Bay PDF schedule",
        "source_url": "https://www.oakbay.ca/wp-content/uploads/2026/03/RacquetSports-Drop-in-Schedule-Spring-2026.pdf",
        "primary_method": "pdf",
        "fallback_method": "pdf",
        "status": "covered",
        "priority": "high",
        "notes": "Current Spring 2026 racquet sports PDF now feeds Henderson pickleball and badminton sessions.",
    },
    {
        "municipality": "Oak Bay",
        "venue_name": "Monterey Recreation Centre",
        "source_system": "PerfectMind / Oak Bay site",
        "source_url": "https://www.oakbay.ca/parks-recreation/programs-registration",
        "primary_method": "widget",
        "fallback_method": "pdf",
        "status": "missing",
        "priority": "low",
        "notes": "Only pursue if it exposes one of the target pickup sports.",
    },
    {
        "municipality": "Oak Bay",
        "venue_name": "Neighbourhood Learning Centre",
        "source_system": "Oak Bay site",
        "source_url": "https://www.oakbay.ca/parks-recreation/facilities-fields/recreation-facilities/neighbourhood-learning-centre/",
        "primary_method": "html",
        "fallback_method": "pdf",
        "status": "missing",
        "priority": "low",
        "notes": "Only pursue if it exposes target sports like badminton or indoor soccer.",
    },
    {
        "municipality": "West Shore",
        "venue_name": "Juan de Fuca Rec Centre",
        "source_system": "Explore WSPR",
        "source_url": "https://explore.wspr.ca/Westshore/public/category/browse/DROP_SPORTS",
        "primary_method": "html",
        "fallback_method": "pdf",
        "status": "covered_partial",
        "priority": "high",
        "notes": "Basketball, pickleball, badminton, and youth volleyball are covered; expand toward soccer/futsal and any hockey-like public sessions if available.",
    },
    {
        "municipality": "West Shore",
        "venue_name": "Juan de Fuca Outdoor Facilities",
        "source_system": "Explore WSPR",
        "source_url": "https://explore.wspr.ca/Westshore/public/booking/items/PICKLEBALLCOURTSONLINE",
        "primary_method": "html",
        "fallback_method": None,
        "status": "covered",
        "priority": "medium",
        "notes": "Outdoor pickleball courts 5 and 6 drop-in availability is now scraped from the public booking grid.",
    },
    {
        "municipality": "West Shore",
        "venue_name": "The Q Centre Arena",
        "source_system": "WSPR site / unknown backing",
        "source_url": "https://www.wspr.ca/about-us/location",
        "primary_method": "html",
        "fallback_method": "pdf",
        "status": "missing",
        "priority": "low",
        "notes": "Only pursue if it exposes recurring hockey or soccer-style public sessions.",
    },
]
